
#include "pelx.h"

// Super Mario Bros. (c) Nintendo 1985
static const uint8_t mushroom_texture_data[] =
{
	PELX_tag_void,
	PELX_tag_void,
	PELX_tag_void,
	PELX_tag_void,
	PELX_tag_void,
	PELX_tag_void,
	PELX_tag_pale, 0x00,
	PELX_tag_pale, 0x00,
	PELX_tag_pale, 0x00,
	PELX_tag_pale, 0x00,
	PELX_tag_void,
	PELX_tag_void,
	PELX_tag_void,
	PELX_tag_void,
	PELX_tag_void,
	PELX_tag_void,

	PELX_tag_void,
	PELX_tag_void,
	PELX_tag_void,
	PELX_tag_void,
	PELX_tag_void,
	PELX_tag_pale, 0x00,
	PELX_tag_pale, 0x00,
	PELX_tag_pale, 0x00,
	PELX_tag_pale, 0x00,
	PELX_tag_pale, 0x01,
	PELX_tag_pale, 0x01,
	PELX_tag_void,
	PELX_tag_void,
	PELX_tag_void,
	PELX_tag_void,
	PELX_tag_void,

	PELX_tag_void,
	PELX_tag_void,
	PELX_tag_void,
	PELX_tag_void,
	PELX_tag_pale, 0x00,
	PELX_tag_pale, 0x00,
	PELX_tag_pale, 0x00,
	PELX_tag_pale, 0x00,
	PELX_tag_pale, 0x01,
	PELX_tag_pale, 0x01,
	PELX_tag_pale, 0x01,
	PELX_tag_pale, 0x01,
	PELX_tag_void,
	PELX_tag_void,
	PELX_tag_void,
	PELX_tag_void,
	
	PELX_tag_void,
	PELX_tag_void,
	PELX_tag_void,
	PELX_tag_pale, 0x00,
	PELX_tag_pale, 0x00,
	PELX_tag_pale, 0x00,
	PELX_tag_pale, 0x00,
	PELX_tag_pale, 0x00,
	PELX_tag_pale, 0x01,
	PELX_tag_pale, 0x01,
	PELX_tag_pale, 0x01,
	PELX_tag_pale, 0x01,
	PELX_tag_pale, 0x01,
	PELX_tag_void,
	PELX_tag_void,
	PELX_tag_void,

	PELX_tag_void,
	PELX_tag_void,
	PELX_tag_pale, 0x00,
	PELX_tag_pale, 0x00,
	PELX_tag_pale, 0x00,
	PELX_tag_pale, 0x00,
	PELX_tag_pale, 0x00,
	PELX_tag_pale, 0x00,
	PELX_tag_pale, 0x00,
	PELX_tag_pale, 0x01,
	PELX_tag_pale, 0x01,
	PELX_tag_pale, 0x01,
	PELX_tag_pale, 0x00,
	PELX_tag_pale, 0x00,
	PELX_tag_void,
	PELX_tag_void,

	PELX_tag_void,
	PELX_tag_pale, 0x00,
	PELX_tag_pale, 0x00,
	PELX_tag_pale, 0x01,
	PELX_tag_pale, 0x01,
	PELX_tag_pale, 0x01,
	PELX_tag_pale, 0x00,
	PELX_tag_pale, 0x00,
	PELX_tag_pale, 0x00,
	PELX_tag_pale, 0x00,
	PELX_tag_pale, 0x00,
	PELX_tag_pale, 0x00,
	PELX_tag_pale, 0x00,
	PELX_tag_pale, 0x00,
	PELX_tag_pale, 0x00,
	PELX_tag_void,

	PELX_tag_void,
	PELX_tag_pale, 0x00,
	PELX_tag_pale, 0x01,
	PELX_tag_pale, 0x01,
	PELX_tag_pale, 0x01,
	PELX_tag_pale, 0x01,
	PELX_tag_pale, 0x01,
	PELX_tag_pale, 0x00,
	PELX_tag_pale, 0x00,
	PELX_tag_pale, 0x00,
	PELX_tag_pale, 0x00,
	PELX_tag_pale, 0x00,
	PELX_tag_pale, 0x00,
	PELX_tag_pale, 0x00,
	PELX_tag_pale, 0x00,
	PELX_tag_void,

	PELX_tag_pale, 0x00,
	PELX_tag_pale, 0x00,
	PELX_tag_pale, 0x01,
	PELX_tag_pale, 0x01,
	PELX_tag_pale, 0x01,
	PELX_tag_pale, 0x01,
	PELX_tag_pale, 0x01,
	PELX_tag_pale, 0x00,
	PELX_tag_pale, 0x00,
	PELX_tag_pale, 0x00,
	PELX_tag_pale, 0x00,
	PELX_tag_pale, 0x00,
	PELX_tag_pale, 0x01,
	PELX_tag_pale, 0x01,
	PELX_tag_pale, 0x00,
	PELX_tag_pale, 0x00,

	PELX_tag_pale, 0x00,
	PELX_tag_pale, 0x00,
	PELX_tag_pale, 0x01,
	PELX_tag_pale, 0x01,
	PELX_tag_pale, 0x01,
	PELX_tag_pale, 0x01,
	PELX_tag_pale, 0x01,
	PELX_tag_pale, 0x00,
	PELX_tag_pale, 0x00,
	PELX_tag_pale, 0x00,
	PELX_tag_pale, 0x00,
	PELX_tag_pale, 0x00,
	PELX_tag_pale, 0x01,
	PELX_tag_pale, 0x01,
	PELX_tag_pale, 0x01,
	PELX_tag_pale, 0x00,

	PELX_tag_pale, 0x00,
	PELX_tag_pale, 0x00,
	PELX_tag_pale, 0x00,
	PELX_tag_pale, 0x01,
	PELX_tag_pale, 0x01,
	PELX_tag_pale, 0x01,
	PELX_tag_pale, 0x00,
	PELX_tag_pale, 0x00,
	PELX_tag_pale, 0x00,
	PELX_tag_pale, 0x00,
	PELX_tag_pale, 0x00,
	PELX_tag_pale, 0x00,
	PELX_tag_pale, 0x00,
	PELX_tag_pale, 0x01,
	PELX_tag_pale, 0x01,
	PELX_tag_pale, 0x00,

	PELX_tag_pale, 0x00,
	PELX_tag_pale, 0x00,
	PELX_tag_pale, 0x00,
	PELX_tag_pale, 0x00,
	PELX_tag_pale, 0x00,
	PELX_tag_pale, 0x00,
	PELX_tag_pale, 0x00,
	PELX_tag_pale, 0x00,
	PELX_tag_pale, 0x00,
	PELX_tag_pale, 0x00,
	PELX_tag_pale, 0x00,
	PELX_tag_pale, 0x00,
	PELX_tag_pale, 0x00,
	PELX_tag_pale, 0x00,
	PELX_tag_pale, 0x00,
	PELX_tag_pale, 0x00,

	PELX_tag_void,
	PELX_tag_pale, 0x00,
	PELX_tag_pale, 0x01,
	PELX_tag_pale, 0x01,
	PELX_tag_pale, 0x01,
	PELX_tag_true, 0xFF, 0xFF, 0xFF, 0xFF,
	PELX_tag_true, 0xFF, 0xFF, 0xFF, 0xFF,
	PELX_tag_true, 0xFF, 0xFF, 0xFF, 0xFF,
	PELX_tag_true, 0xFF, 0xFF, 0xFF, 0xFF,
	PELX_tag_true, 0xFF, 0xFF, 0xFF, 0xFF,
	PELX_tag_true, 0xFF, 0xFF, 0xFF, 0xFF,
	PELX_tag_pale, 0x01,
	PELX_tag_pale, 0x01,
	PELX_tag_pale, 0x01,
	PELX_tag_pale, 0x00,
	PELX_tag_void,

	PELX_tag_void,
	PELX_tag_void,
	PELX_tag_void,
	PELX_tag_void,
	PELX_tag_true, 0xFF, 0xFF, 0xFF, 0xFF,
	PELX_tag_true, 0xFF, 0xFF, 0xFF, 0xFF,
	PELX_tag_true, 0xFF, 0xFF, 0xFF, 0xFF,
	PELX_tag_true, 0xFF, 0xFF, 0xFF, 0xFF,
	PELX_tag_true, 0xFF, 0xFF, 0xFF, 0xFF,
	PELX_tag_true, 0xFF, 0xFF, 0xFF, 0xFF,
	PELX_tag_true, 0xFF, 0xFF, 0xFF, 0xFF,
	PELX_tag_true, 0xFF, 0xFF, 0xFF, 0xFF,
	PELX_tag_void,
	PELX_tag_void,
	PELX_tag_void,
	PELX_tag_void,

	PELX_tag_void,
	PELX_tag_void,
	PELX_tag_void,
	PELX_tag_void,
	PELX_tag_true, 0xFF, 0xFF, 0xFF, 0xFF,
	PELX_tag_true, 0xFF, 0xFF, 0xFF, 0xFF,
	PELX_tag_true, 0xFF, 0xFF, 0xFF, 0xFF,
	PELX_tag_true, 0xFF, 0xFF, 0xFF, 0xFF,
	PELX_tag_true, 0xFF, 0xFF, 0xFF, 0xFF,
	PELX_tag_true, 0xFF, 0xFF, 0xFF, 0xFF,
	PELX_tag_pale, 0x00,
	PELX_tag_true, 0xFF, 0xFF, 0xFF, 0xFF,
	PELX_tag_void,
	PELX_tag_void,
	PELX_tag_void,
	PELX_tag_void,

	PELX_tag_void,
	PELX_tag_void,
	PELX_tag_void,
	PELX_tag_void,
	PELX_tag_true, 0xFF, 0xFF, 0xFF, 0xFF,
	PELX_tag_true, 0xFF, 0xFF, 0xFF, 0xFF,
	PELX_tag_true, 0xFF, 0xFF, 0xFF, 0xFF,
	PELX_tag_true, 0xFF, 0xFF, 0xFF, 0xFF,
	PELX_tag_true, 0xFF, 0xFF, 0xFF, 0xFF,
	PELX_tag_true, 0xFF, 0xFF, 0xFF, 0xFF,
	PELX_tag_pale, 0x00,
	PELX_tag_true, 0xFF, 0xFF, 0xFF, 0xFF,
	PELX_tag_void,
	PELX_tag_void,
	PELX_tag_void,
	PELX_tag_void,

	PELX_tag_void,
	PELX_tag_void,
	PELX_tag_void,
	PELX_tag_void,
	PELX_tag_void,
	PELX_tag_true, 0xFF, 0xFF, 0xFF, 0xFF,
	PELX_tag_true, 0xFF, 0xFF, 0xFF, 0xFF,
	PELX_tag_true, 0xFF, 0xFF, 0xFF, 0xFF,
	PELX_tag_true, 0xFF, 0xFF, 0xFF, 0xFF,
	PELX_tag_pale, 0x00,
	PELX_tag_true, 0xFF, 0xFF, 0xFF, 0xFF,
	PELX_tag_void,
	PELX_tag_void,
	PELX_tag_void,
	PELX_tag_void,
	PELX_tag_void,
};
